Updated pipeline code.

diff --git a/.acquia/pipeline.yaml b/.acquia/pipeline.yaml
--- a/.acquia/pipeline.yaml
+++ b/.acquia/pipeline.yaml
@@ -27,79 +27,50 @@ _orca_steps: &orca_steps
         ../orca/bin/ci/script.sh
         ./bin/travis/script.sh
         ../orca/bin/ci/before_cache.sh
+        if [ "$error" = "true" ]; then
+          echo "Running after failure";
+          ../orca/bin/ci/after_failure.sh;
+          if [ "$ALLOWED_FAILURE" = "true" ]; then
+            exit 0;
+          else
+            exit 1;
+          fi
+        else
+          echo "Running after success";
+          ../orca/bin/ci/after_success.sh;
+        fi
 
 # -- Continuous Integration --
 # Pre-build runs after building the environment image, and relies on it to
 # run its sub-stages' steps inside of the environment container.
 pre_build:
   static_code_analysis:
-    - args: --env ORCA_JOB=STATIC_CODE_ANALYSIS
+    - args: --env ORCA_JOB=STATIC_CODE_ANALYSIS --env ALLOWED_FAILURE=true
       <<: *orca_steps
-#  integrated_test_on_oldest_supported:
-#    - args: --env ORCA_JOB=INTEGRATED_TEST_ON_OLDEST_SUPPORTED
-#      <<: *orca_steps
-#  #  integrated_test_on_latest_lts:
-#  #    - args: --env ORCA_JOB=INTEGRATED_TEST_ON_LATEST_LTS
-#  #      <<: *orca_steps
-#  integrated_test_on_prev_minor:
-#    - args: --env ORCA_JOB=INTEGRATED_TEST_ON_PREVIOUS_MINOR
-#      <<: *orca_steps
-#  integrated_test_from_prev_minor:
-#    - args: --env ORCA_JOB=INTEGRATED_UPGRADE_TEST_FROM_PREVIOUS_MINOR
-#      <<: *orca_steps
-#  isolated_test_on_current:
-#    - args: --env ORCA_JOB=ISOLATED_TEST_ON_CURRENT
-#      <<: *orca_steps
-#  integrated_test_on_current:
-#    - args: --env ORCA_JOB=INTEGRATED_TEST_ON_CURRENT
-#      <<: *orca_steps
-#  integrated_test_to_next_minor:
-#    - args: --env ORCA_JOB=INTEGRATED_UPGRADE_TEST_TO_NEXT_MINOR
-#      <<: *orca_steps
-#  integrated_test_to_next_minor_dev:
-#    - args: --env ORCA_JOB=INTEGRATED_UPGRADE_TEST_TO_NEXT_MINOR_DEV
-#      <<: *orca_steps
-#  isolated_test_on_current_dev:
-#    - args: --env ORCA_JOB=ISOLATED_TEST_ON_CURRENT_DEV
-#      <<: *orca_steps
-##  integrated_test_on_current_dev:
-##    - args: --env ORCA_JOB=INTEGRATED_TEST_ON_CURRENT_DEV
-##      <<: *orca_steps
   deprecated_code_scan:
-    - args: --env ORCA_JOB=DEPRECATED_CODE_SCAN
+    - args: --env ORCA_JOB=DEPRECATED_CODE_SCAN --env ALLOWED_FAILURE=true
       <<: *orca_steps
-  #  deprecated_code_scan_w_contrib:
-  #    - args: --env ORCA_JOB=DEPRECATED_CODE_SCAN_W_CONTRIB
-  #      <<: *orca_steps
-  isolated_test_on_next_minor:
-    - args: --env ORCA_JOB=ISOLATED_TEST_ON_NEXT_MINOR
+  isolated_test_w_recommended_version:
+    - args: --env ORCA_JOB=ISOLATED_RECOMMENDED
       <<: *orca_steps
-  integrated_test_on_next_minor:
-    - args: --env ORCA_JOB=INTEGRATED_TEST_ON_NEXT_MINOR
+  integrated_test_w_recommended_version:
+    - args: --env ORCA_JOB=INTEGRATED_RECOMMENDED
       <<: *orca_steps
-  isolated_test_on_next_minor_dev:
-    - args: --env ORCA_JOB=ISOLATED_TEST_ON_NEXT_MINOR_DEV
+  integrated_test_w_recommended_version_and_previous_minor_core:
+    - args: --env ORCA_JOB=CORE_PREVIOUS
       <<: *orca_steps
-  integrated_test_on_next_minor_dev:
-    - args: --env ORCA_JOB=INTEGRATED_TEST_ON_NEXT_MINOR_DEV
+  isolated_test_with_dev_version:
+    - args: --env ORCA_JOB=ISOLATED_DEV --env ALLOWED_FAILURE=true
       <<: *orca_steps
-  isolated_upgrade_test_to_next_major_beta_or_later:
-    - args: --env ORCA_JOB=ISOLATED_UPGRADE_TEST_TO_NEXT_MAJOR_BETA_OR_LATER
+  integrated_test_with_dev_version:
+    - args: --env ORCA_JOB=INTEGRATED_DEV --env ALLOWED_FAILURE=true
       <<: *orca_steps
-  isolated_upgrade_test_to_next_major_dev:
-    - args: --env ORCA_JOB=ISOLATED_UPGRADE_TEST_TO_NEXT_MAJOR_DEV
+  integrated_test_with_dev_version_and_next_minor_core:
+    - args: --env ORCA_JOB=CORE_NEXT --env ALLOWED_FAILURE=true
       <<: *orca_steps
 
   security_composition_analysis:
     required: false
-
-after_success:
-  - steps:
-      - cd $ORCA_WORKSPACE && ../orca/bin/travis/after_success.sh
-
-after_failure:
-  - steps:
-      - cd $ORCA_WORKSPACE && ../orca/bin/travis/after_failure.sh
 
 # -- Slack Bot Integration --
 notify:
